import React, { useEffect, useMemo, useRef, useState } from "react";
import { Camera, ChevronRight, FileText, FolderInput, FolderOpen, MoreVertical, Pencil, Plus, Search, Share2, Star, Trash2, X } from "lucide-react";
import { Filesystem } from "@capacitor/filesystem";
import { Share } from "@capacitor/share";
import { Capacitor } from "@capacitor/core";
import { $l, bs, Ch, Ea, gp, Jf, moveDocument, normalizeFolder, Ph, readDocumentDataUrl, restoreTrash, shareDocument, trashDocument, trashFolder, updateFolder, listTrash } from "../data/files.js";
import { bp, Sp } from "../data/agenda-camera.js";
import { Card, Chip, colors, confirmAction, createId, EmptyState, ErrorState, IconTile, Input, LoadingState, nowISO, Rt, ScreenHeader, storage, Yu } from "../core/recovered.js";

const MAX_SIZE = 25 * 1024 * 1024;
const ACCEPT = ".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.jpg,.jpeg,.png,.webp,.gif,.mp4,.webm,.mov";
const folderColors = ["primary", "orange", "green", "purple", "red"];
const folderColorValue = (color) => ({ primary: colors.primary, orange: colors.orange, green: colors.green, purple: colors.blue, red: colors.red }[color] || colors.primary);

function fileKind(item) {
  const ext = item.nome?.includes(".") ? item.nome.split(".").pop().toUpperCase() : "ARQUIVO";
  if (item.mime === "application/pdf" || ext === "PDF") return "PDF";
  if (item.mime?.startsWith("image/")) return "IMAGEM";
  if (item.mime?.startsWith("video/")) return "VÍDEO";
  return ext;
}
function fileSize(bytes) { if (!bytes) return "Tamanho não informado"; return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`; }
function sortRecent(items) { return [...items].sort((a, b) => String(b.atualizadoEm || b.criadoEm).localeCompare(String(a.atualizadoEm || a.criadoEm))); }

function Dialog({ title, children, onClose }) {
  return <div className="files-dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="files-dialog ui-card" role="dialog" aria-modal="true" aria-labelledby="files-dialog-title"><div className="files-dialog-heading"><h2 id="files-dialog-title">{title}</h2><button className="icon-button touch-target" aria-label="Fechar" onClick={onClose}><X size={19} /></button></div>{children}</section></div>;
}

function DocumentViewer({ document, url, onClose, onShare }) {
  const kind = fileKind(document);
  return <Dialog title={document.nome} onClose={onClose}><div className="files-viewer"><div className="files-viewer-meta">{kind} · {fileSize(document.tamanho)}</div>{kind === "IMAGEM" && <img src={url} alt={document.nome} className="files-viewer-image" />}{kind === "VÍDEO" && <video src={url} className="files-viewer-video" controls playsInline />}{kind === "PDF" && <iframe src={url} title={`Visualização de ${document.nome}`} className="files-viewer-frame" />}{!["IMAGEM", "VÍDEO", "PDF"].includes(kind) && <div className="files-viewer-unsupported"><FileText size={34} /><strong>Este formato precisa de outro aplicativo</strong><span>Use o botão abaixo para abrir o arquivo no visualizador disponível.</span></div>}<div className="files-create-actions"><button className="ui-button ui-button-secondary touch-target" onClick={onShare}><Share2 size={17} />Compartilhar</button><button className="ui-button ui-button-primary touch-target" onClick={onClose}>Fechar</button></div></div></Dialog>;
}

export function LibraryScreen({ onBack, onDirtyChange, setBackHandler, onRequestLocalBack, onOpenTrash }) {
  const inputRef = useRef(null); const cameraInputRef = useRef(null);
  const [folders, setFolders] = useState(null); const [documents, setDocuments] = useState(null); const [currentFolder, setCurrentFolder] = useState(Ea);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("tudo"); const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [showCreate, setShowCreate] = useState(false); const [folderName, setFolderName] = useState(""); const [editingFolder, setEditingFolder] = useState(null);
  const [folderDraft, setFolderDraft] = useState({ nome: "", cor: "primary" }); const [movingDocument, setMovingDocument] = useState(null); const [viewer, setViewer] = useState(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [undoEntry, setUndoEntry] = useState(null);

  const hydrate = async () => { setError(""); try { const [nextFolders, nextDocs] = await Promise.all([Ch(storage), bs(storage)]); setFolders(nextFolders); setDocuments(nextDocs); if (currentFolder !== Ea && !nextFolders.some((folder) => folder.id === currentFolder)) setCurrentFolder(Ea); } catch (err) { setFolders(null); setDocuments(null); setError(`${err?.message || "Não foi possível abrir sua biblioteca."} Seus dados não foram alterados.`); } };
  useEffect(() => { hydrate(); }, []);
  useEffect(() => { onDirtyChange?.((showCreate && !!folderName.trim()) || !!editingFolder); return () => onDirtyChange?.(false); }, [showCreate, folderName, editingFolder, onDirtyChange]);
  const parentFolder = currentFolder === Ea ? null : folders?.find((folder) => folder.id === currentFolder); const hasContext = currentFolder !== Ea || !!query.trim();
  useEffect(() => { if (!setBackHandler) return undefined; const localBack = query ? () => setQuery("") : parentFolder ? () => setCurrentFolder(parentFolder.pastaPaiId || Ea) : null; setBackHandler(localBack ? () => localBack : null); return () => setBackHandler(null); }, [query, parentFolder?.id, setBackHandler]);
  const lowerQuery = query.trim().toLocaleLowerCase("pt-BR"); const breadcrumb = useMemo(() => Ph(folders || [], currentFolder), [folders, currentFolder]);
  const visibleFolders = useMemo(() => { const source = folders || []; const filtered = source.filter((folder) => { const inScope = lowerQuery || filter === "recentes" ? true : folder.pastaPaiId === currentFolder; const matches = !lowerQuery || folder.nome.toLocaleLowerCase("pt-BR").includes(lowerQuery); return inScope && matches && filter !== "arquivos" && (!favoritesOnly || folder.favorito); }); return filter === "recentes" ? sortRecent(filtered).slice(0, 8) : filtered; }, [folders, currentFolder, lowerQuery, filter, favoritesOnly]);
  const visibleDocuments = useMemo(() => { const source = documents || []; const filtered = source.filter((doc) => { const inScope = lowerQuery || filter === "recentes" ? true : (doc.pastaId || Ea) === currentFolder; const matches = !lowerQuery || doc.nome.toLocaleLowerCase("pt-BR").includes(lowerQuery); return inScope && matches && filter !== "pastas" && (!favoritesOnly || doc.favorito); }); return filter === "recentes" ? sortRecent(filtered).slice(0, 12) : filtered; }, [documents, currentFolder, lowerQuery, filter, favoritesOnly]);

  const createFolder = async () => { if (!folderName.trim()) return; setBusy(true); setError(""); try { if ((folders || []).some((folder) => folder.pastaPaiId === currentFolder && folder.nome.toLocaleLowerCase() === folderName.trim().toLocaleLowerCase())) throw new Error("Já existe uma pasta com esse nome aqui."); const folder = normalizeFolder({ nome: folderName, pastaPaiId: currentFolder }, { id: createId("pasta") }); setFolders(await Jf(storage, [...(folders || []), folder])); setFolderName(""); setShowCreate(false); Rt(700); } catch (err) { setError(err?.message || "Não foi possível criar a pasta."); } finally { setBusy(false); } };
  const addFiles = async (event) => { const selected = Array.from(event.target.files || []); event.target.value = ""; if (!selected.length) return; setBusy(true); setError(""); let added = 0; try { for (const file of selected) { if (file.size > MAX_SIZE) throw new Error(`${file.name}: o limite por arquivo é 25 MB.`); await gp({ dataUrl: await Yu(file), nome: file.name, tamanho: file.size, id: createId("doc"), pastaId: currentFolder }, { storage, filesystem: Filesystem }); added += 1; } setDocuments(await bs(storage)); setNotice(`${added} arquivo${added === 1 ? " adicionado" : "s adicionados"}.`); Rt(700); } catch (err) { setDocuments(await bs(storage).catch(() => documents || [])); setError(added ? `${added} arquivo${added === 1 ? " foi adicionado" : "s foram adicionados"}; os demais não foram adicionados.` : (err?.message || "Não foi possível adicionar o arquivo.")); } finally { setBusy(false); } };
  const capturePhoto = async () => { if (!Capacitor.isNativePlatform()) { cameraInputRef.current?.click(); return; } setBusy(true); setError(""); try { const photo = await Sp(); await gp({ dataUrl: photo.dataUrl, nome: `Foto ${new Date().toLocaleDateString("pt-BR")}.jpg`, tamanho: 0, id: createId("foto"), pastaId: currentFolder }, { storage, filesystem: Filesystem }); setDocuments(await bs(storage)); setNotice("Foto adicionada à biblioteca."); } catch (err) { setError(bp(err)); } finally { setBusy(false); } };
  const toggleFavorite = async (doc) => { try { setDocuments(await $l(storage, (documents || []).map((item) => item.id === doc.id ? { ...item, favorito: !item.favorito, atualizadoEm: nowISO() } : item))); } catch (err) { setError(err?.message || "Não foi possível atualizar o favorito."); } };
  const toggleFolderFavorite = async (folder) => { try { setFolders(await updateFolder(storage, folder, { favorito: !folder.favorito })); } catch (err) { setError(err?.message || "Não foi possível atualizar o favorito."); } };
  const removeDocument = async (doc) => { if (!await confirmAction({ title: "Mover para a lixeira?", message: `“${doc.nome}” poderá ser restaurado depois.`, confirmLabel: "Mover" })) return; setBusy(true); try { setDocuments(await trashDocument(doc, documents || [], { storage })); setUndoEntry((await listTrash(storage))[0] || null); setNotice("Arquivo movido para a lixeira."); } catch (err) { setError(err?.message || "Não foi possível mover o arquivo."); } finally { setBusy(false); } };
  const removeFolder = async (folder) => { if (!await confirmAction({ title: "Mover pasta para a lixeira?", message: `A pasta “${folder.nome}” precisa estar vazia.`, confirmLabel: "Mover" })) return; setBusy(true); try { setFolders(await trashFolder(folder, folders || [], documents || [], { storage })); setUndoEntry((await listTrash(storage))[0] || null); setNotice("Pasta movida para a lixeira."); } catch (err) { setError(err?.message || "Não foi possível mover a pasta."); } finally { setBusy(false); } };
  const saveFolderEdit = async () => { if (!editingFolder || !folderDraft.nome.trim()) return; setBusy(true); try { setFolders(await updateFolder(storage, editingFolder, folderDraft)); setEditingFolder(null); setNotice("Pasta atualizada."); } catch (err) { setError(err?.message || "Não foi possível atualizar a pasta."); } finally { setBusy(false); } };
  const openDoc = async (doc) => { setBusy(true); setError(""); try { const url = await readDocumentDataUrl(doc, { filesystem: Filesystem }); setViewer({ document: doc, url }); } catch (err) { setError(err?.message?.toLowerCase().includes("not found") ? "Este arquivo não existe mais no aparelho." : "Não foi possível ler este arquivo. Tente importá-lo novamente."); } finally { setBusy(false); } };
  const closeViewer = () => { if (viewer?.url?.startsWith("blob:")) URL.revokeObjectURL(viewer.url); setViewer(null); };
  const share = async (doc) => { try { await shareDocument(doc, { share: Share, filesystem: Filesystem }); setNotice("Arquivo pronto para compartilhar."); } catch (err) { setError(err?.message || "O compartilhamento foi negado ou não está disponível."); } };
  const undoTrash = async () => { if (!undoEntry) return; setBusy(true); try { await restoreTrash(undoEntry, { storage }); setDocuments(await bs(storage)); setFolders(await Ch(storage)); setUndoEntry(null); setNotice("Item restaurado."); } catch (err) { setError(err?.message || "Não foi possível desfazer esta ação."); } finally { setBusy(false); } };
  const empty = !busy && !visibleFolders.length && !visibleDocuments.length; const emptyTitle = lowerQuery ? "Nenhum resultado encontrado" : filter === "recentes" ? "Nenhum arquivo recente" : favoritesOnly ? "Nenhum favorito ainda" : currentFolder === Ea ? "Este espaço é seu" : "Pasta vazia";
  const emptyDescription = lowerQuery ? "Tente buscar por outro nome." : favoritesOnly ? "Marque pastas e arquivos com uma estrela para encontrá-los aqui." : currentFolder === Ea ? "Crie uma pasta, adicione um arquivo ou capture uma foto." : "Adicione arquivos ou crie uma subpasta neste espaço.";

  return <div className="files-screen" style={{ paddingBottom: 120 }}>
    <ScreenHeader title={parentFolder ? parentFolder.nome : "Arquivos"} subtitle={parentFolder ? "Arquivos e pastas deste espaço" : "Sua biblioteca pedagógica local"} onBack={hasContext ? onRequestLocalBack : onBack} />
    <div className="files-content">
      <div className="files-heading-row"><div><div className="files-title">{parentFolder ? parentFolder.nome : <button className="files-root-label" onClick={() => setCurrentFolder(Ea)}>Meus Arquivos</button>}</div><div className="files-subtitle">{parentFolder ? "Organize os materiais desta pasta." : "Pastas, fotos, vídeos e documentos sempre à mão."}</div></div><button className="icon-button press-fx touch-target files-trash-button" aria-label="Abrir lixeira" onClick={onOpenTrash}><Trash2 size={20} /></button></div>
      <div className="files-search"><Search size={18} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar arquivos e pastas" aria-label="Buscar arquivos e pastas" />{query && <button className="icon-button" aria-label="Limpar busca" onClick={() => setQuery("")}><X size={17} /></button>}</div>
      <div className="files-toolbar"><div className="files-filters" role="group" aria-label="Filtrar biblioteca">{[["tudo", "Tudo"], ["recentes", "Recentes"], ["pastas", "Pastas"], ["arquivos", "Arquivos"]].map(([key, label]) => <button key={key} className={`files-filter ${filter === key ? "active" : ""}`} onClick={() => setFilter(key)} aria-pressed={filter === key}>{label}</button>)}</div><Chip label="Favoritos" active={favoritesOnly} onClick={() => setFavoritesOnly((value) => !value)} /></div>
      {!lowerQuery && <div className="files-breadcrumb" aria-label="Caminho da pasta"><button onClick={() => setCurrentFolder(Ea)} className={currentFolder === Ea ? "current" : ""}>Arquivos</button>{breadcrumb.map((folder) => <React.Fragment key={folder.id}><ChevronRight size={14} /><button onClick={() => setCurrentFolder(folder.id)} className={folder.id === currentFolder ? "current" : ""}>{folder.nome}</button></React.Fragment>)}</div>}
      <input ref={inputRef} type="file" multiple accept={ACCEPT} onChange={addFiles} style={{ display: "none" }} /><input ref={cameraInputRef} type="file" accept="image/*" capture="environment" onChange={addFiles} style={{ display: "none" }} />
      <div className="files-quick-actions"><button className="ui-button ui-button-primary press-fx touch-target" onClick={() => inputRef.current?.click()} disabled={busy}><Plus size={17} />Adicionar arquivo</button><button className="ui-button ui-button-secondary press-fx touch-target" onClick={capturePhoto} disabled={busy}><Camera size={17} />Capturar foto</button></div>
      {showCreate && <Card className="files-create-card"><strong>{currentFolder === Ea ? "Nova pasta" : "Nova subpasta"}</strong><Input autoFocus aria-label="Nome da pasta" placeholder="Ex.: Projetos de leitura" value={folderName} onChange={(event) => setFolderName(event.target.value)} /><div className="files-create-actions"><button className="ui-button ui-button-secondary touch-target" onClick={() => { setShowCreate(false); setFolderName(""); }}>Cancelar</button><button className="ui-button ui-button-primary touch-target" disabled={busy || !folderName.trim()} onClick={createFolder}>Criar</button></div></Card>}
      {error && <ErrorState message={error} onRetry={hydrate} />}{notice && <div className="state-feedback state-feedback-success" role="status" aria-live="polite"><span>{notice}</span>{undoEntry && <button className="text-button" onClick={undoTrash}>Desfazer</button>}<button className="text-button" onClick={() => { setNotice(""); setUndoEntry(null); }}>Fechar</button></div>}{(folders === null || documents === null) && <LoadingState label="Abrindo sua biblioteca…" />}
      {folders !== null && documents !== null && visibleFolders.length > 0 && <section className="files-section" aria-label="Pastas"><div className="files-section-title">PASTAS</div><div className="files-folder-grid">{visibleFolders.map((folder) => <Card key={folder.id} className="files-folder-card"><button className="files-folder-open" onClick={() => { setCurrentFolder(folder.id); setQuery(""); setFilter("tudo"); }}><FolderOpen size={24} color={folderColorValue(folder.cor)} /><strong>{folder.nome}</strong><span>{folder.favorito ? "Favorita · " : ""}Abrir pasta</span></button><button className="icon-button touch-target" aria-label={folder.favorito ? `Remover ${folder.nome} dos favoritos` : `Favoritar ${folder.nome}`} onClick={() => toggleFolderFavorite(folder)}><Star size={16} fill={folder.favorito ? colors.orange : "none"} color={folder.favorito ? colors.orange : colors.gray} /></button><button className="icon-button touch-target" aria-label={`Editar ${folder.nome}`} onClick={() => { setEditingFolder(folder); setFolderDraft({ nome: folder.nome, cor: folder.cor, pastaPaiId: folder.pastaPaiId }); }}><Pencil size={15} /></button><button className="icon-button touch-target files-item-delete" aria-label={`Mover ${folder.nome} para a lixeira`} onClick={() => removeFolder(folder)}><Trash2 size={16} /></button></Card>)}</div></section>}
      {folders !== null && documents !== null && visibleDocuments.length > 0 && <section className="files-section" aria-label="Arquivos"><div className="files-section-title">{filter === "recentes" ? "RECENTES" : lowerQuery ? "RESULTADOS" : "ARQUIVOS"}</div><div className="files-list">{visibleDocuments.map((doc) => <Card key={doc.id} className="files-item"><button className="files-item-open" aria-label={`Abrir ${doc.nome}`} onClick={() => openDoc(doc)}><IconTile color={fileKind(doc) === "PDF" ? colors.red : fileKind(doc) === "IMAGEM" ? colors.green : colors.primary} Icon={fileKind(doc) === "IMAGEM" ? Camera : FileText} /></button><button className="files-item-copy" onClick={() => openDoc(doc)}><strong>{doc.nome}</strong><span>{fileKind(doc)} · {fileSize(doc.tamanho)}{lowerQuery ? ` · ${folders?.find((folder) => folder.id === doc.pastaId)?.nome || "Arquivos"}` : ""}</span></button><button className="icon-button touch-target" aria-label={doc.favorito ? `Remover ${doc.nome} dos favoritos` : `Favoritar ${doc.nome}`} onClick={() => toggleFavorite(doc)}><Star size={18} fill={doc.favorito ? colors.orange : "none"} color={doc.favorito ? colors.orange : colors.gray} /></button><button className="icon-button touch-target" aria-label={`Mais ações para ${doc.nome}`} onClick={() => setMovingDocument(doc)}><MoreVertical size={18} /></button><button className="icon-button touch-target files-item-delete" aria-label={`Mover ${doc.nome} para a lixeira`} onClick={() => removeDocument(doc)}><Trash2 size={17} /></button></Card>)}</div></section>}
      {empty && <EmptyState icon={FolderOpen} illustration="files" title={emptyTitle} description={emptyDescription} />}
    </div>
    <input aria-hidden="true" tabIndex={-1} style={{ display: "none" }} />
    {editingFolder && <Dialog title={`Editar ${editingFolder.nome}`} onClose={() => setEditingFolder(null)}><div className="stack"><Input aria-label="Nome da pasta" value={folderDraft.nome} onChange={(event) => setFolderDraft({ ...folderDraft, nome: event.target.value })} /><label className="helper-text" htmlFor="folder-parent">Mover para</label><select id="folder-parent" className="ui-input" aria-label="Pasta pai" value={folderDraft.pastaPaiId} onChange={(event) => setFolderDraft({ ...folderDraft, pastaPaiId: event.target.value })}><option value={Ea}>Meus Arquivos</option>{(folders || []).filter((folder) => folder.id !== editingFolder.id).map((folder) => <option key={folder.id} value={folder.id}>{folder.nome}</option>)}</select><div className="files-color-picker" role="group" aria-label="Cor da pasta">{folderColors.map((color) => <button key={color} type="button" className={`files-color-option ${folderDraft.cor === color ? "selected" : ""}`} style={{ background: folderColorValue(color) }} aria-label={`Cor ${color}`} aria-pressed={folderDraft.cor === color} onClick={() => setFolderDraft({ ...folderDraft, cor: color })} />)}</div><div className="files-create-actions"><button className="ui-button ui-button-secondary touch-target" onClick={() => setEditingFolder(null)}>Cancelar</button><button className="ui-button ui-button-primary touch-target" disabled={busy || !folderDraft.nome.trim()} onClick={saveFolderEdit}>Salvar</button></div></div></Dialog>}
    {movingDocument && <Dialog title={`Organizar ${movingDocument.nome}`} onClose={() => setMovingDocument(null)}><div className="stack"><p className="helper-text">Escolha a pasta de destino.</p><select className="ui-input" aria-label="Pasta de destino" value={movingDocument.pastaId || Ea} onChange={async (event) => { try { setDocuments(await moveDocument(storage, movingDocument, event.target.value)); setMovingDocument(null); setNotice("Arquivo movido."); } catch (err) { setError(err?.message || "Não foi possível mover o arquivo."); } }}><option value={Ea}>Meus Arquivos</option>{(folders || []).filter((folder) => folder.id !== movingDocument.pastaId).map((folder) => <option key={folder.id} value={folder.id}>{folder.nome}</option>)}</select><button className="ui-button ui-button-secondary touch-target" onClick={() => { setMovingDocument(null); share(movingDocument); }}><Share2 size={17} />Compartilhar</button></div></Dialog>}
    {viewer && <DocumentViewer document={viewer.document} url={viewer.url} onClose={closeViewer} onShare={() => share(viewer.document)} />}
    <div className="files-fab-menu"><button className="files-fab press-fx" aria-label="Criar nova pasta" onClick={() => setShowCreate(true)}><FolderInput size={25} /></button></div>
  </div>;
}
