import React, { useEffect, useState } from "react";
import { Archive, FileText, FolderOpen, RotateCcw, Trash2 } from "lucide-react";
import { Filesystem } from "@capacitor/filesystem";
import { deleteTrashPermanently, listTrash, restoreTrash } from "../data/files.js";
import { Avatar, Card, EmptyState, ErrorState, LoadingState, ScreenHeader, confirmAction, colors, op, storage } from "../core/recovered.js";

function labelFor(entry) { return entry.type === "folder" ? "Pasta" : "Arquivo"; }
export function TrashScreen({ onBack }) {
  const [items, setItems] = useState(null); const [students, setStudents] = useState([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const hydrate = async () => { setError(""); try { const [library, excluded] = await Promise.all([listTrash(storage), op.listarEstudantesExcluidos().catch(() => [])]); setItems(library); setStudents(excluded || []); } catch (err) { setError(err?.message || "Não foi possível abrir a lixeira."); } };
  useEffect(() => { hydrate(); }, []);
  const restoreLibrary = async (entry) => { setBusy(true); try { await restoreTrash(entry, { storage }); await hydrate(); } catch (err) { setError(err?.message || "Não foi possível restaurar este item."); } finally { setBusy(false); } };
  const permanentlyDelete = async (entry) => { if (!await confirmAction({ title: "Excluir definitivamente?", message: `“${entry.item.nome}” será removido do aparelho e não poderá ser recuperado.`, confirmLabel: "Excluir definitivamente" })) return; setBusy(true); try { await deleteTrashPermanently(entry, { storage, filesystem: Filesystem }); await hydrate(); } catch (err) { setError(err?.message || "Não foi possível excluir este item definitivamente."); } finally { setBusy(false); } };
  const restoreStudent = async (id) => { setBusy(true); try { await op.restaurarEstudante(id); await hydrate(); } catch (err) { setError(err?.message || "Não foi possível restaurar o aluno."); } finally { setBusy(false); } };
  const permanentStudent = async (student) => { if (!await confirmAction({ title: "Excluir aluno definitivamente?", message: `“${student.nome}” e os dados associados serão removidos.`, confirmLabel: "Excluir definitivamente" })) return; setBusy(true); try { await op.excluirEstudanteDefinitivamente(student.id); await hydrate(); } catch (err) { setError(err?.message || "Não foi possível excluir o aluno."); } finally { setBusy(false); } };
  const empty = items?.length === 0 && students.length === 0;
  return <div className="files-screen" style={{ paddingBottom: 30 }}><ScreenHeader title="Lixeira" subtitle="Itens removidos podem ser recuperados" onBack={onBack} /><div className="files-content">{error && <ErrorState message={error} onRetry={hydrate} />}{items === null && <LoadingState label="Abrindo sua lixeira…" />}{items !== null && empty && <EmptyState compact icon={Archive} title="A lixeira está vazia" description="Arquivos, pastas e alunos removidos aparecerão aqui." onAction={onBack} actionLabel="Voltar aos arquivos" />}{items?.length > 0 && <section className="files-section" aria-label="Itens da biblioteca na lixeira"><div className="files-section-title">ARQUIVOS E PASTAS</div><div className="files-list">{items.map((entry) => <Card key={entry.id} className="files-item"><IconTile color={entry.type === "folder" ? colors.orange : colors.primary} Icon={entry.type === "folder" ? FolderOpen : FileText} /><div className="files-item-copy"><strong>{entry.item.nome}</strong><span>{labelFor(entry)} · removido em {new Date(entry.deletedAt).toLocaleDateString("pt-BR")}</span></div><button className="icon-button touch-target" aria-label={`Restaurar ${entry.item.nome}`} disabled={busy} onClick={() => restoreLibrary(entry)}><RotateCcw size={17} /></button><button className="icon-button touch-target files-item-delete" aria-label={`Excluir definitivamente ${entry.item.nome}`} disabled={busy} onClick={() => permanentlyDelete(entry)}><Trash2 size={17} /></button></Card>)}</div></section>}{students.length > 0 && <section className="files-section" aria-label="Alunos na lixeira"><div className="files-section-title">ALUNOS</div><div className="files-list">{students.map((student) => <Card key={student.id} className="files-item"><Avatar nome={student.nome} cor={student.cor || colors.primary} /><div className="files-item-copy"><strong>{student.nome}</strong><span>Aluno removido</span></div><button className="ui-button ui-button-secondary touch-target" disabled={busy} onClick={() => restoreStudent(student.id)}>Restaurar</button><button className="icon-button touch-target files-item-delete" aria-label={`Excluir definitivamente ${student.nome}`} disabled={busy} onClick={() => permanentStudent(student)}><Trash2 size={17} /></button></Card>)}</div></section>}</div></div>;
}
