import { Check, Moon, Palette, Sun, ArrowLeft, Monitor } from 'lucide-react';
import type { CSSProperties } from 'react';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './appearance-v2.css';

type Props = { theme: string; setTheme: (theme: string) => void; accentColor: string; setAccentColor: (color: string) => void; systemDark?: boolean; onBack: () => void };
const themes = [{ id: 'claro', label: 'Claro', detail: 'Leve, claro e pronto para a sala', icon: Sun }, { id: 'sistema', label: 'Sistema', detail: 'Acompanha a aparência do Android', icon: Monitor }, { id: 'escuro', label: 'Escuro', detail: 'Menos luz em ambientes noturnos', icon: Moon }];
const accents = [{ id: '#168be0', label: 'Azul vivo' }, { id: '#0b71ca', label: 'Azul profundo' }, { id: '#0b9b78', label: 'Verde' }, { id: '#7b61d9', label: 'Violeta' }, { id: '#d28a12', label: 'Âmbar' }];

export function AppearanceV2({ theme, setTheme, accentColor, setAccentColor, systemDark, onBack }: Props) {
  return <main className="v2-root v2-appearance"><div className="v2-screen v2-appearance__screen"><header className="v2-appearance__header"><button type="button" className="v2-appearance__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">PERSONALIZAÇÃO</span><h1>Aparência</h1><p>Escolha como a rotina aparece para você.</p></div><span className="v2-appearance__mark"><Palette size={23} /></span></header><section className="v2-appearance__hero"><div className="v2-appearance__preview"><span style={{ background: accentColor }} /><span /><span /></div><div><span className="v2-eyebrow">SUA IDENTIDADE</span><h2>Claro, tátil e confortável.</h2><p>As escolhas ficam neste dispositivo.</p></div></section><section className="v2-appearance__section" aria-labelledby="appearance-theme-title"><div className="v2-appearance__section-head"><div><span className="v2-eyebrow">MODO DE TELA</span><h2 id="appearance-theme-title">Como você prefere trabalhar?</h2></div></div><div className="v2-appearance__theme-list" role="radiogroup" aria-label="Modo de tela">{themes.map(({ id, label, detail, icon: Icon }) => <button type="button" role="radio" aria-checked={theme === id} className={`v2-appearance__theme v2-pressable${theme === id ? ' is-selected' : ''}`} key={id} onClick={() => setTheme(id)}><span className="v2-appearance__theme-icon"><Icon size={21} /></span><span><strong>{label}</strong><small>{id === 'sistema' && systemDark !== undefined ? `${detail} · agora ${systemDark ? 'escuro' : 'claro'}` : detail}</small></span>{theme === id && <Check size={19} />}</button>)}</div></section><section className="v2-appearance__section" aria-labelledby="appearance-accent-title"><div className="v2-appearance__section-head"><div><span className="v2-eyebrow">COR DE AÇÃO</span><h2 id="appearance-accent-title">Um toque de azul no que importa.</h2></div></div><div className="v2-appearance__accent-list" role="radiogroup" aria-label="Cor de ação">{accents.map(({ id, label }) => <button type="button" role="radio" aria-label={label} aria-checked={accentColor === id} className={`v2-appearance__accent v2-pressable${accentColor === id ? ' is-selected' : ''}`} style={{ '--accent': id } as CSSProperties} key={id} onClick={() => setAccentColor(id)}><span />{accentColor === id && <Check size={16} />}</button>)}</div><p className="v2-appearance__hint">A cor de ação aparece em botões e estados de foco. O contraste continua priorizado.</p></section></div></main>;
}
