import { ArrowLeft, BookOpenCheck, ChevronRight, FileText, House, LayoutGrid, Plus, Users } from 'lucide-react';
import * as React from 'react';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './classes-v2.css';

type ClassItem = { id: string; nome: string; nivel?: string; turno?: string; arquivadaEm?: string | null };
type Student = { id: string; nome: string; cor?: string };
type Props = { classes: ClassItem[]; activeClass?: ClassItem | null; students: Student[]; onBack?: () => void; onActivate?: (item: ClassItem) => void; onOpenStudent?: (student: Student) => void; onNewStudent?: () => void; onAttendance?: () => void; onObservation?: () => void; onTabChange?: (tab: 'inicio' | 'planejamento' | 'turmas' | 'arquivos' | 'mais') => void };
const navItems = [{ id: 'inicio', label: 'Início', icon: House }, { id: 'planejamento', label: 'Planejamento', icon: BookOpenCheck }, { id: 'turmas', label: 'Turmas', icon: Users }, { id: 'arquivos', label: 'Arquivos', icon: FileText }, { id: 'mais', label: 'Mais', icon: LayoutGrid }] as const;
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export function ClassesV2({ classes, activeClass, students, onBack = () => undefined, onActivate = () => undefined, onOpenStudent = () => undefined, onNewStudent = () => undefined, onAttendance = () => undefined, onObservation = () => undefined, onTabChange = () => undefined }: Props) {
  const visible = classes.filter((item) => !item.arquivadaEm);
  return <main className="v2-root v2-classes" aria-labelledby="classes-v2-title"><div className="v2-screen v2-classes__screen">
    <header className="v2-classes__header"><button className="v2-classes__back v2-pressable" type="button" onClick={onBack} aria-label="Voltar"><ArrowLeft size={25} /></button><div><span className="v2-eyebrow">SUA ROTINA</span><h1 id="classes-v2-title">Turmas</h1><p>Alunos, presença e registros no mesmo lugar.</p></div><button className="v2-classes__add v2-pressable" type="button" onClick={onNewStudent} aria-label="Adicionar aluno"><Plus size={25} /></button></header>
    <section className="v2-classes__active"><div className="v2-classes__active-copy"><span className="v2-eyebrow">TURMA ATIVA</span><h2>{activeClass?.nome || 'Nenhuma turma selecionada'}</h2><p>{activeClass ? `${activeClass.nivel || 'Ensino Fundamental'}${activeClass.turno ? ` · ${activeClass.turno}` : ''}` : 'Crie sua primeira turma para começar.'}</p></div><strong className="v2-classes__student-count">{students.length}<small>alunos</small></strong></section>
    {activeClass && <div className="v2-classes__actions"><button className="v2-classes__action v2-pressable" type="button" onClick={onAttendance}><span>✓</span><strong>Fazer chamada</strong><small>Registrar presença</small></button><button className="v2-classes__action is-green v2-pressable" type="button" onClick={onObservation}><span>＋</span><strong>Registrar observação</strong><small>Guardar contexto da aula</small></button></div>}
    <section className="v2-classes__students" aria-labelledby="classes-students-title"><div className="v2-classes__section-head"><div><span className="v2-eyebrow">ACOMPANHAMENTO</span><h2 id="classes-students-title">Alunos da turma</h2></div><button type="button" className="v2-classes__text-action v2-pressable" onClick={onNewStudent}>Adicionar</button></div>{students.length ? <div className="v2-classes__student-list">{students.map((student) => <button key={student.id} className="v2-classes__student-row v2-pressable" type="button" onClick={() => onOpenStudent(student)}><span className="v2-classes__avatar" style={{ '--student-color': student.cor || '#168be0' } as React.CSSProperties}>{initials(student.nome)}</span><span><strong>{student.nome}</strong><small>Ver perfil e histórico</small></span><ChevronRight size={21} /></button>)}</div> : <div className="v2-classes__empty"><Users size={30} /><strong>Sua lista começa aqui</strong><p>Cadastre o primeiro aluno para fazer chamada e acompanhar registros.</p><button className="v2-primary-action v2-pressable" type="button" onClick={onNewStudent}><Plus size={19} /> Adicionar aluno</button></div>}</section>
    {visible.length > 1 && <section className="v2-classes__other"><div className="v2-classes__section-head"><div><span className="v2-eyebrow">SEU CONTEXTO</span><h2>Outras turmas</h2></div></div>{visible.filter((item) => item.id !== activeClass?.id).map((item) => <button key={item.id} className="v2-classes__other-row v2-pressable" type="button" onClick={() => onActivate(item)}><span><strong>{item.nome}</strong><small>{item.nivel || 'Turma'}{item.turno ? ` · ${item.turno}` : ''}</small></span><ChevronRight size={21} /></button>)}</section>}
    <nav className="v2-classes__bottom-nav" aria-label="Navegação principal">{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={`v2-classes__nav-item v2-pressable${id === 'turmas' ? ' is-selected' : ''}`} aria-current={id === 'turmas' ? 'page' : undefined} onClick={() => onTabChange(id)}><Icon size={23} /><span>{label}</span></button>)}</nav>
  </div></main>;
}
