import { useEffect, useState } from 'react';
import { ArrowLeft, Check, LifeBuoy, Share2 } from 'lucide-react';
import { Capacitor } from '@capacitor/core';
import { Share } from '@capacitor/share';
import { storage } from '../../data/localStore';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './help-legal-v2.css';

export function HelpV2({ onBack }: { onBack: () => void }) {
  const [message, setMessage] = useState(''); const [includeTechnical, setIncludeTechnical] = useState(false); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  useEffect(() => { void storage.get('feedback:rascunho').then(({ value }) => { const draft = JSON.parse(value) as { message?: string; includeTechnical?: boolean }; setMessage(draft.message || ''); setIncludeTechnical(draft.includeTechnical === true); }).catch(() => undefined); }, []);
  const prepare = async () => { setError(''); setStatus(''); if (message.trim().length < 10) { setError('Escreva pelo menos 10 caracteres para preparar um feedback.'); return; } await storage.set('feedback:rascunho', JSON.stringify({ message, includeTechnical, atualizadoEm: new Date().toISOString() })); const technical = includeTechnical ? `\n\nInformações técnicas: plataforma ${Capacitor.getPlatform()}, versão Android-first.` : ''; const text = `Feedback do Assistente Pedagógico\n\n${message.trim()}${technical}\n\nNão foram incluídos dados de alunos.`; try { if (Capacitor.isNativePlatform()) await Share.share({ title: 'Feedback do Assistente Pedagógico', text, dialogTitle: 'Compartilhar feedback' }); else if (navigator.share) await navigator.share({ title: 'Feedback do Assistente Pedagógico', text }); else await navigator.clipboard.writeText(text); setStatus('Feedback preparado para compartilhamento.'); } catch (cause) { if ((cause as Error)?.name !== 'AbortError') setError('Não foi possível preparar o compartilhamento. Tente novamente.'); } };
  return <main className="v2-root v2-help"><div className="v2-screen v2-help__screen"><header className="v2-help__header"><button type="button" className="v2-help__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">SUPORTE</span><h1>Ajuda e feedback</h1><p>Conte como podemos melhorar.</p></div><span className="v2-help__mark"><LifeBuoy size={22} /></span></header>{status && <p className="v2-help__status" role="status"><Check size={17} />{status}</p>}{error && <p className="v2-help__error" role="alert">{error}</p>}<section className="v2-help__form v2-surface"><span className="v2-eyebrow">FALE COM A EQUIPE</span><h2>O que aconteceu?</h2><p>Descreva uma dificuldade ou uma ideia para o aplicativo.</p><label>Mensagem<textarea value={message} onChange={(event) => setMessage(event.target.value)} maxLength={5000} rows={7} placeholder="O que você gostaria de contar?" /></label><label className="v2-help__check"><input type="checkbox" checked={includeTechnical} onChange={(event) => setIncludeTechnical(event.target.checked)} />Incluir informações técnicas básicas</label><div className="v2-help__warning">Não escreva nomes, contatos, fotos ou outros dados pessoais de alunos. O compartilhamento só acontece quando você tocar no botão.</div><button type="button" className="v2-primary-action v2-help__primary v2-pressable" onClick={() => void prepare()}><Share2 size={18} />Preparar feedback</button></section><section className="v2-help__quick v2-surface"><span className="v2-eyebrow">AJUDA RÁPIDA</span><h2>Seus dados ficam no aparelho</h2><p>Use o Backup local antes de trocar de telefone ou limpar os dados do Android. Tutoriais, privacidade e termos ficam disponíveis em Configurações.</p></section></div></main>;
}
