import { useState } from 'react';
import { ArrowLeft, FileText, ShieldCheck } from 'lucide-react';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './help-legal-v2.css';

export function LegalV2({ onBack }: { onBack: () => void }) {
  const [tab, setTab] = useState<'termos' | 'privacidade'>('termos');
  return <main className="v2-root v2-legal"><div className="v2-screen v2-legal__screen"><header className="v2-help__header"><button type="button" className="v2-help__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">INFORMAÇÕES</span><h1>Termos e privacidade</h1><p>Como o aplicativo cuida do seu trabalho.</p></div><span className="v2-help__mark"><ShieldCheck size={22} /></span></header><div className="v2-legal__tabs" role="tablist" aria-label="Documentos legais"><button type="button" role="tab" aria-selected={tab === 'termos'} className={`v2-legal__tab v2-pressable${tab === 'termos' ? ' is-active' : ''}`} onClick={() => setTab('termos')}><FileText size={17} />Termos de uso</button><button type="button" role="tab" aria-selected={tab === 'privacidade'} className={`v2-legal__tab v2-pressable${tab === 'privacidade' ? ' is-active' : ''}`} onClick={() => setTab('privacidade')}><ShieldCheck size={17} />Privacidade</button></div><article className="v2-legal__copy v2-surface">{tab === 'termos' ? <><span className="v2-eyebrow">TERMOS DE USO · VERSÃO 1.0</span><h2>Uma ferramenta para o trabalho docente</h2><p>O Assistente Pedagógico ajuda a planejar aulas, acompanhar turmas e registrar informações pedagógicas. Ele não substitui decisões pedagógicas ou obrigações da instituição de ensino.</p><h3>Conteúdo inserido</h3><p>Você decide quais informações registrar e deve ter autorização ou outra base legítima para tratar dados de terceiros, inclusive de alunos.</p><h3>Armazenamento local</h3><p>Na versão atual, os registros ficam neste aparelho. O Backup local permite criar uma cópia manual; mantenha essa cópia protegida.</p><h3>Assinaturas</h3><p>Recursos pagos, preço, periodicidade e renovação só serão ativados quando a compra pela Google Play estiver configurada e forem apresentados antes da confirmação.</p></> : <><span className="v2-eyebrow">POLÍTICA DE PRIVACIDADE · VERSÃO 1.0</span><h2>Seus dados pedagógicos merecem cuidado</h2><p>Perfil, turmas, alunos, frequência, planejamentos, arquivos e registros são armazenados localmente para executar as funções escolhidas por você.</p><h3>Métricas opcionais</h3><p>O aplicativo não envia métricas por padrão. Se você ativar o consentimento em Privacidade, apenas eventos técnicos permitidos podem ser registrados; o conteúdo de alunos não é enviado.</p><h3>Arquivos e permissões</h3><p>Câmera, arquivos, notificações e compartilhamento só são usados quando você aciona a função correspondente e concede a permissão do Android.</p><h3>Exclusão e backup</h3><p>Você pode apagar os dados deste aparelho na área de Backup. Antes disso, exporte uma cópia se precisar preservar o histórico.</p></>}</article></div></main>;
}
