import { useEffect, useState } from 'react';
import { ArrowLeft, Bell, CalendarDays, Check, Clock3, Plus, Trash2 } from 'lucide-react';
import { Fh, Mh, zh } from '../../data/notifications.js';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './notifications-v2.css';

type Reminder = { id: number; title?: string; body?: string; schedule?: { at?: string | Date } };
type Props = { onBack: () => void; onDirtyChange?: (dirty: boolean) => void };
const today = () => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
export function NotificationsV2({ onBack, onDirtyChange = () => undefined }: Props) {
  const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [date, setDate] = useState(today); const [time, setTime] = useState(''); const [items, setItems] = useState<Reminder[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [canceling, setCanceling] = useState<number | null>(null);
  const dirty = Boolean(title.trim() || message.trim() || time); useEffect(() => { onDirtyChange(dirty); return () => onDirtyChange(false); }, [dirty, onDirtyChange]);
  const load = async () => { setLoading(true); setError(''); try { setItems(await Mh()); } catch { setItems([]); setError('Não foi possível carregar os lembretes locais.'); } finally { setLoading(false); } }; useEffect(() => { void load(); }, []);
  const create = async () => { setSaving(true); setError(''); setNotice(''); try { await zh({ titulo: title, mensagem: message, quando: new Date(`${date}T${time}:00`) }); setTitle(''); setMessage(''); setTime(''); setNotice('Lembrete criado neste aparelho.'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível criar o lembrete.'); } finally { setSaving(false); } };
  const cancel = async (item: Reminder) => { setCanceling(item.id); setError(''); try { await Fh(item.id); setNotice('Lembrete cancelado.'); await load(); } catch { setError('Não foi possível cancelar o lembrete.'); } finally { setCanceling(null); } };
  return <main className="v2-root v2-notifications"><div className="v2-notifications__screen"><header className="v2-notifications__header"><button type="button" className="v2-notifications__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">SUA ROTINA</span><h1>Lembretes</h1><p>Notificações locais no horário escolhido.</p></div><span className="v2-notifications__mark"><Bell size={22} /></span></header>{notice && <p className="v2-notifications__notice" role="status"><Check size={17} />{notice}</p>}{error && <p className="v2-notifications__error" role="alert">{error}</p>}<section className="v2-notifications__form"><span className="v2-eyebrow">CRIAR LEMBRETE</span><h2>O que você precisa lembrar?</h2><label><span>Título</span><div><Bell size={18} /><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: preparar materiais" /></div></label><label><span>Mensagem <em>opcional</em></span><div><Plus size={18} /><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Um contexto para você" /></div></label><div className="v2-notifications__date-row"><label><span>Data</span><div><CalendarDays size={18} /><input type="date" min={today()} value={date} onChange={(event) => setDate(event.target.value)} /></div></label><label><span>Horário</span><div><Clock3 size={18} /><input type="time" aria-label="Horário do lembrete" value={time} onChange={(event) => setTime(event.target.value)} /></div></label></div><p className="v2-notifications__helper">A permissão do Android só será solicitada ao criar o primeiro lembrete.</p><button type="button" className="v2-primary-action v2-notifications__primary v2-pressable" disabled={saving || !title.trim() || !date || !time} onClick={() => void create()}>{saving ? 'Agendando…' : 'Criar lembrete'}<Bell size={18} /></button></section><section className="v2-notifications__list" aria-labelledby="pending-title"><div><span className="v2-eyebrow">PENDENTES</span><h2 id="pending-title">Seus próximos lembretes</h2></div>{loading ? <div className="v2-notifications__empty">Carregando lembretes…</div> : !items.length ? <div className="v2-notifications__empty"><Bell size={25} /><strong>Nenhum lembrete pendente.</strong><p>Crie um lembrete para não deixar uma tarefa passar.</p></div> : items.map((item) => <div className="v2-notifications__item" key={item.id}><span><Bell size={18} /></span><div><strong>{item.title || 'Lembrete pedagógico'}</strong><small>{item.schedule?.at ? new Date(item.schedule.at).toLocaleString('pt-BR') : 'Horário programado'}</small></div><button type="button" className="v2-pressable" aria-label={`Cancelar ${item.title || 'lembrete'}`} disabled={canceling === item.id} onClick={() => void cancel(item)}><Trash2 size={18} /></button></div>)}</section></div></main>;
}
