import { ArrowLeft, BookOpenCheck, CalendarDays, ChevronLeft, ChevronRight, FileText, House, LayoutGrid, Plus, Users } from 'lucide-react';
import * as React from 'react';
import type { LessonPlan } from '../../domain/models';
import type { TeachingActivity } from '../../domain/activities';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './planning-calendar-v2.css';

type View = 'week' | 'month';
type PlanningView = 'day' | View;
type Props = { className?: string; mode: View; dateKey: string; plans: LessonPlan[]; activities?: TeachingActivity[]; loading?: boolean; error?: string; offline?: boolean; onBack?: () => void; onRetry?: () => void; onDateChange?: (key: string) => void; onViewChange?: (view: PlanningView) => void; onOpenPlan?: (plan: LessonPlan) => void; onOpenActivity?: (activity: TeachingActivity) => void; onCreatePlan?: () => void; onTabChange?: (tab: 'inicio' | 'planejamento' | 'turmas' | 'arquivos' | 'mais') => void };
const navItems = [{ id: 'inicio', label: 'Início', icon: House }, { id: 'planejamento', label: 'Planejamento', icon: BookOpenCheck }, { id: 'turmas', label: 'Turmas', icon: Users }, { id: 'arquivos', label: 'Arquivos', icon: FileText }, { id: 'mais', label: 'Mais', icon: LayoutGrid }] as const;
const pad = (value: number) => String(value).padStart(2, '0');
const keyOf = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const dateOf = (key: string) => new Date(`${key}T12:00:00`);
const labelOf = (key: string) => dateOf(key).toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long' });
const monthLabel = (date: Date) => date.toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' });

export function PlanningCalendarV2({ className = 'Sua turma', mode, dateKey, plans, activities = [], loading = false, error = '', offline = false, onBack = () => undefined, onRetry = () => undefined, onDateChange = () => undefined, onViewChange = () => undefined, onOpenPlan = () => undefined, onOpenActivity = () => undefined, onCreatePlan = () => undefined, onTabChange = () => undefined }: Props) {
  const selected = dateOf(dateKey);
  const [month, setMonth] = React.useState(() => new Date(selected.getFullYear(), selected.getMonth(), 1));
  React.useEffect(() => setMonth(new Date(selected.getFullYear(), selected.getMonth(), 1)), [dateKey]);
  const week = React.useMemo(() => { const monday = new Date(selected); monday.setDate(selected.getDate() - ((selected.getDay() + 6) % 7)); return Array.from({ length: 7 }, (_, index) => { const date = new Date(monday); date.setDate(monday.getDate() + index); return keyOf(date); }); }, [dateKey]);
  const monthDays = React.useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(first).fill(''), ...Array.from({ length: count }, (_, index) => keyOf(new Date(month.getFullYear(), month.getMonth(), index + 1)))]; }, [month]);
  const dayPlans = plans.filter((plan) => plan.dataKey === dateKey && !plan.arquivadoEm).flatMap((plan) => (plan.momentos || []).map((moment) => ({ plan, title: moment.titulo || plan.tituloTema || 'Plano de aula', time: moment.horario || plan.horaInicio, detail: moment.descricao || plan.objetivoGeral })));
  const dayActivities = activities.filter((activity) => activity.dataKey === dateKey && activity.status !== 'arquivada');
  const weekPlanCount = week.reduce((total, key) => total + plans.filter((plan) => plan.dataKey === key && !plan.arquivadoEm).length, 0);
  const weekActivityCount = week.reduce((total, key) => total + activities.filter((activity) => activity.dataKey === key && activity.status !== 'arquivada').length, 0);
  const weekEventCount = weekPlanCount + weekActivityCount;
  const selectedWeekDay = selected.toLocaleDateString('pt-BR', { weekday: 'long' });
  const moveMonth = (amount: number) => setMonth(new Date(month.getFullYear(), month.getMonth() + amount, 1));
  return <main className="v2-root v2-planning-calendar" aria-labelledby="planning-calendar-v2-title"><div className="v2-screen v2-planning-calendar__screen">
    <header className="v2-planning-calendar__header"><button className="v2-planning-calendar__back v2-pressable" type="button" onClick={onBack} aria-label="Voltar"><ArrowLeft size={25} /></button><div><span className="v2-eyebrow">{className}</span><h1 id="planning-calendar-v2-title">{mode === 'week' ? 'Planejamento semanal' : monthLabel(month)}</h1><p>{mode === 'week' ? labelOf(dateKey) : 'Veja o ritmo do mês e escolha um dia.'}</p></div><button className="v2-planning-calendar__calendar v2-pressable" type="button" onClick={() => onViewChange(mode === 'week' ? 'month' : 'week')} aria-label={mode === 'week' ? 'Abrir visão mensal' : 'Abrir visão semanal'}><CalendarDays size={24} /></button></header>
    {offline && <div className="v2-planning-calendar__notice" role="status">Você está offline. O planejamento local continua disponível.</div>}{error && <div className="v2-planning-calendar__notice is-error" role="alert"><span>{error}</span><button type="button" onClick={onRetry}>Tentar novamente</button></div>}
    <div className="v2-planning-calendar__tabs" role="tablist" aria-label="Visão do planejamento"><button type="button" role="tab" aria-selected="false" onClick={() => onViewChange('day')}>Dia</button><button className={mode === 'week' ? 'is-selected' : ''} type="button" role="tab" aria-selected={mode === 'week'} onClick={() => onViewChange('week')}>Semana</button><button className={mode === 'month' ? 'is-selected' : ''} type="button" role="tab" aria-selected={mode === 'month'} onClick={() => onViewChange('month')}>Mês</button></div>
    {mode === 'week' ? <div className="v2-planning-calendar__week-strip">{week.map((key) => <button className={`v2-planning-calendar__week-day v2-pressable${key === dateKey ? ' is-selected' : ''}`} type="button" key={key} onClick={() => onDateChange(key)} aria-pressed={key === dateKey}><span>{dateOf(key).toLocaleDateString('pt-BR', { weekday: 'short' }).replace('.', '')}</span><strong>{dateOf(key).getDate()}</strong><small>{plans.some((plan) => plan.dataKey === key && !plan.arquivadoEm) || activities.some((activity) => activity.dataKey === key && activity.status !== 'arquivada') ? '•' : ''}</small></button>)}</div> : <div className="v2-planning-calendar__month"><div className="v2-planning-calendar__month-nav"><button className="v2-planning-calendar__date-arrow v2-pressable" type="button" onClick={() => moveMonth(-1)} aria-label="Mês anterior"><ChevronLeft size={22} /></button><strong>{monthLabel(month)}</strong><button className="v2-planning-calendar__date-arrow v2-pressable" type="button" onClick={() => moveMonth(1)} aria-label="Próximo mês"><ChevronRight size={22} /></button></div><div className="v2-planning-calendar__weekdays">{['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map((day) => <span key={day}>{day}</span>)}</div><div className="v2-planning-calendar__grid">{monthDays.map((key, index) => key ? <button type="button" className={`v2-planning-calendar__cell v2-pressable${key === dateKey ? ' is-selected' : ''}`} key={key} onClick={() => onDateChange(key)} aria-label={labelOf(key)} aria-pressed={key === dateKey}><strong>{dateOf(key).getDate()}</strong>{(plans.some((plan) => plan.dataKey === key && !plan.arquivadoEm) || activities.some((activity) => activity.dataKey === key && activity.status !== 'arquivada')) && <i />}</button> : <span key={`blank-${index}`} />)}</div></div>}
    {mode === 'week' && <section className="v2-planning-calendar__week-summary" aria-labelledby="planning-week-summary-title"><div><span className="v2-eyebrow">RITMO DA SEMANA</span><h2 id="planning-week-summary-title">{weekEventCount ? `${weekEventCount} ${weekEventCount === 1 ? 'preparo' : 'preparos'} já no caminho` : 'A semana está aberta'}</h2><p>{weekEventCount ? `${selectedWeekDay} concentra o que está selecionado. Escolha outro dia para continuar.` : 'Escolha um dia acima e comece a organizar a próxima aula.'}</p></div><button className="v2-planning-calendar__week-summary-action v2-pressable" type="button" onClick={onCreatePlan} aria-label="Planejar próximo momento"><Plus size={18} /> Planejar</button></section>}
    <div className="v2-planning-calendar__day-heading"><div><span className="v2-eyebrow">{mode === 'week' ? 'SEMANA EM FOCO' : 'DIA SELECIONADO'}</span><h2>{labelOf(dateKey)}</h2></div><span className="v2-planning-calendar__count">{dayPlans.length + dayActivities.length}</span></div>
    {loading ? <div className="v2-planning-calendar__state" role="status">Carregando planejamento...</div> : dayPlans.length ? <section className="v2-planning-calendar__plans" aria-label="Planos do dia">{dayPlans.map((item) => <button className="v2-planning-calendar__plan v2-pressable" type="button" key={`${item.plan.id}-${item.title}`} onClick={() => onOpenPlan(item.plan)}><time>{item.time || '—'}</time><span className="v2-planning-calendar__plan-icon"><BookOpenCheck size={21} /></span><span><strong>{item.title}</strong><small>{item.detail || item.plan.tituloTema || 'Plano de aula'}</small></span><ChevronRight size={21} /></button>)}</section> : <div className="v2-planning-calendar__state"><CalendarDays size={32} /><strong>Dia livre para planejar</strong><p>Escolha este momento para preparar uma aula com calma.</p></div>}
    {dayActivities.length > 0 && <section className="v2-planning-calendar__activities" aria-labelledby="planning-calendar-activities-title"><div className="v2-planning-calendar__activities-heading"><div><span className="v2-eyebrow">PREPARO</span><h2 id="planning-calendar-activities-title">Atividades preparadas</h2></div><span className="v2-planning-calendar__count">{dayActivities.length}</span></div>{dayActivities.map((activity) => <button className="v2-planning-calendar__activity v2-pressable" type="button" key={activity.id} onClick={() => onOpenActivity(activity)}><span className="v2-planning-calendar__plan-icon"><BookOpenCheck size={20} /></span><span><strong>{activity.titulo}</strong><small>{activity.disciplina || 'Atividade pedagógica'} · {activity.status === 'pronta' ? 'Pronta' : 'Rascunho'}</small></span><ChevronRight size={21} /></button>)}</section>}
    <button className="v2-planning-calendar__add v2-pressable" type="button" onClick={onCreatePlan}><Plus size={19} /> Criar plano neste dia</button>
    <nav className="v2-planning-calendar__bottom-nav" aria-label="Navegação principal">{navItems.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={`v2-planning-calendar__nav-item v2-pressable${id === 'planejamento' ? ' is-selected' : ''}`} aria-current={id === 'planejamento' ? 'page' : undefined} onClick={() => onTabChange(id)}><Icon size={23} /><span>{label}</span></button>)}</nav>
  </div></main>;
}
