import { useState } from 'react';
import { ArrowLeft, ChevronRight, Database, FileLock2, ShieldCheck, Trash2 } from 'lucide-react';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './privacy-v2.css';

type Props = { onBack: () => void; goTo?: (route: string) => void };
export function PrivacyV2({ onBack, goTo }: Props) {
  const [analytics, setAnalytics] = useState(() => { try { return JSON.parse(window.localStorage.getItem('config:analytics') || 'false') === true; } catch { return false; } });
  const toggle = (value: boolean) => { setAnalytics(value); try { window.localStorage.setItem('config:analytics', JSON.stringify(value)); } catch { /* armazenamento indisponível */ } };
  return <main className="v2-root v2-privacy"><div className="v2-privacy__screen"><header className="v2-privacy__header"><button type="button" className="v2-privacy__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">CONTROLE E CUIDADO</span><h1>Privacidade</h1><p>Seus dados pedagógicos sob seu controle.</p></div><span className="v2-privacy__mark"><ShieldCheck size={22} /></span></header><section className="v2-privacy__hero"><span><Database size={22} /></span><div><strong>Este aparelho é o seu espaço.</strong><p>Perfil, turmas, planejamentos e registros ficam armazenados localmente nesta versão.</p></div></section><section className="v2-privacy__section" aria-labelledby="privacy-usage-title"><div className="v2-privacy__section-head"><span className="v2-privacy__icon"><FileLock2 size={20} /></span><div><span className="v2-eyebrow">DADOS DE USO</span><h2 id="privacy-usage-title">Registros técnicos locais</h2></div></div><p>Por padrão, o aplicativo não envia dados de uso. Se quiser ajudar a diagnosticar problemas, você pode permitir registros técnicos neste aparelho. Conteúdo de alunos não é incluído.</p><label className="v2-privacy__toggle"><span><strong>Permitir registros técnicos</strong><small>{analytics ? 'Ativado neste aparelho' : 'Desativado por padrão'}</small></span><input type="checkbox" checked={analytics} onChange={(event) => toggle(event.target.checked)} /><i aria-hidden="true" /></label></section><section className="v2-privacy__section"><span className="v2-eyebrow">SUAS ESCOLHAS</span><h2>Você decide o que guardar.</h2><p>Fotos, áudios e dados de alunos devem ser registrados somente quando houver finalidade pedagógica e autorização adequada.</p><button type="button" className="v2-privacy__row v2-pressable" onClick={() => goTo?.('backup')}><span className="v2-privacy__icon"><Database size={19} /></span><span><strong>Gerenciar backup e dados</strong><small>Exporte uma cópia ou apague os dados locais.</small></span><ChevronRight size={20} /></button><button type="button" className="v2-privacy__row v2-pressable is-danger" onClick={() => goTo?.('backup')}><span className="v2-privacy__icon"><Trash2 size={19} /></span><span><strong>Excluir dados locais</strong><small>A ação será confirmada antes de apagar qualquer coisa.</small></span><ChevronRight size={20} /></button></section><p className="v2-privacy__note">Desinstalar o aplicativo ou limpar seus dados pelo Android pode apagar as informações deste aparelho.</p></div></main>;
}
