import { useState } from 'react';
import { ArchiveRestore, ArrowLeft, Bell, ChevronRight, Crown, Database, FileText, Info, LifeBuoy, Palette, Settings2, Shield, Sparkles, UserRound, Users, Volume2, VolumeX } from 'lucide-react';
import '@fontsource/fredoka/600.css';
import '../styles/foundation.css';
import './settings-v2.css';

type Props = { sonsAtivados: boolean; setSonsAtivados: (enabled: boolean) => void; onBack: () => void; goTo: (route: string) => void };
const groups = [
  { label: 'PERFIL E TRABALHO', items: [{ route: 'perfil-professor', title: 'Editar perfil', detail: 'Foto e informações profissionais', icon: UserRound }, { route: 'gerenciar-turmas', title: 'Minhas turmas', detail: 'Criar, editar e trocar a turma ativa', icon: Users }, { route: 'assinatura', title: 'Seu plano', detail: 'Recursos e assinatura', icon: Crown, tone: 'gold' }] },
  { label: 'PREFERÊNCIAS', items: [{ route: 'tema', title: 'Aparência', detail: 'Tema, cor e acessibilidade', icon: Palette }, { route: 'notificacoes', title: 'Notificações', detail: 'Lembretes locais de compromissos', icon: Bell }] },
  { label: 'DADOS E SEGURANÇA', items: [{ route: 'backup', title: 'Backup local', detail: 'Exporte ou restaure uma cópia', icon: Database }, { route: 'lixeira', title: 'Lixeira', detail: 'Recupere itens removidos', icon: ArchiveRestore }, { route: 'privacidade', title: 'Privacidade', detail: 'Como seus dados são tratados', icon: Shield }] },
  { label: 'AJUDA', items: [{ route: 'tutoriais', title: 'Ajuda e tutoriais', detail: 'Aprenda usando o aplicativo', icon: Sparkles }, { route: 'ajuda-feedback', title: 'Ajuda e feedback', detail: 'Fale com a equipe sem dados de alunos', icon: LifeBuoy }, { route: 'termos', title: 'Termos e privacidade', detail: 'Informações legais', icon: FileText }] },
];

export function SettingsV2({ sonsAtivados, setSonsAtivados, onBack, goTo }: Props) {
  const [aboutOpen, setAboutOpen] = useState(false);
  return <main className="v2-root v2-settings"><div className="v2-screen v2-settings__screen"><header className="v2-settings__header"><button type="button" className="v2-settings__back v2-pressable" onClick={onBack} aria-label="Voltar"><ArrowLeft size={23} /></button><div><span className="v2-eyebrow">SEU ESPAÇO</span><h1>Configurações</h1><p>Deixe o aplicativo do seu jeito.</p></div><span className="v2-settings__mark"><Settings2 size={23} /></span></header><section className="v2-settings__intro"><span className="v2-eyebrow">CONTROLE LOCAL</span><h2>Preferências que acompanham sua rotina.</h2><p>Suas escolhas ficam neste dispositivo e podem ser ajustadas quando quiser.</p></section><div className="v2-settings__groups">{groups.map((group) => <section key={group.label}><h2>{group.label}</h2><div className="v2-settings__list">{group.items.map(({ route, title, detail, icon: Icon, tone }) => <button type="button" className="v2-settings__row v2-pressable" key={route} onClick={() => goTo(route)}><span className={`v2-settings__icon${tone ? ` is-${tone}` : ''}`}><Icon size={20} /></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={18} /></button>)}</div></section>)}<section><h2>EXPERIÊNCIA</h2><div className="v2-settings__list"><button type="button" className="v2-settings__row v2-pressable" onClick={() => setSonsAtivados(!sonsAtivados)} aria-pressed={sonsAtivados}><span className="v2-settings__icon">{sonsAtivados ? <Volume2 size={20} /> : <VolumeX size={20} />}</span><span><strong>Sons do aplicativo</strong><small>{sonsAtivados ? 'Ativados' : 'Desativados'} · feedback discreto</small></span><span className={`v2-settings__toggle${sonsAtivados ? ' is-on' : ''}`} aria-hidden="true" /></button><button type="button" className="v2-settings__row v2-pressable" onClick={() => setAboutOpen((value) => !value)} aria-expanded={aboutOpen}><span className="v2-settings__icon"><Info size={20} /></span><span><strong>Sobre o aplicativo</strong><small>Assistente Pedagógico · versão 1.0</small></span><ChevronRight size={18} className={aboutOpen ? 'is-open' : undefined} /></button>{aboutOpen && <div className="v2-settings__about">Feito para quem ensina. Dados pedagógicos ficam sob seu controle e o núcleo continua utilizável offline.</div>}</div></section></div></div></main>;
}
